In [1]:
import pandas as pd

import geopandas as gpd
 
import contextily as ctx

import matplotlib.pyplot as plt

In [4]:
race2019blockgdf = gpd.read_file('race2019blocks.geojson')
race2019blockgdf.sample(3)

,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geometry
1,15000US060014002001,"Block Group 1, Alameda, CA",990.0,761.0,13.0,4.0,41.0,0.0,0.0,75.0,96.0,76.868687,1.313131,0.40404,4.141414,0.000000,0.0,7.575758,9.696970,"MULTIPOLYGON (((-13609373.698 4557703.289, -13..."
225,15000US060014074002,"Block Group 2, Alameda, CA",1459.0,22.0,246.0,0.0,22.0,0.0,0.0,0.0,1169.0,1.507882,16.860864,0.00000,1.507882,0.000000,0.0,0.000000,80.123372,"MULTIPOLYGON (((-13604441.576 4547052.740, -13..."
264,15000US060014085003,"Block Group 3, Alameda, CA",683.0,10.0,198.0,0.0,0.0,16.0,0.0,0.0,459.0,1.464129,28.989751,0.00000,0.000000,2.342606,0.0,0.000000,67.203514,"MULTIPOLYGON (((-13601287.673 4545163.860, -13..."

In [41]:
race2019blockgdf['newgeoid'] = race2019blockgdf['geoid'].str[8:19]
race2019blockgdf.sample(3)

,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,...,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geometry,geoid10,newgeoid
253,15000US060014082003,"Block Group 3, Alameda, CA",918.0,121.0,575.0,0.0,40.0,0.0,0.0,90.0,...,62.636166,0.000000,4.357298,0.0,0.000000,9.803922,10.021786,"MULTIPOLYGON (((-13601451.646 4547901.961, -13...",060014082003,60014082003
233,15000US060014076004,"Block Group 4, Alameda, CA",1301.0,151.0,285.0,0.0,111.0,0.0,0.0,46.0,...,21.906226,0.000000,8.531899,0.0,0.000000,3.535742,54.419677,"MULTIPOLYGON (((-13604195.004 4547470.300, -13...",060014076004,60014076004
42,15000US060014014003,"Block Group 3, Alameda, CA",1008.0,306.0,208.0,49.0,123.0,0.0,2.0,63.0,...,20.634921,4.861111,12.202381,0.0,0.198413,6.250000,25.496032,"MULTIPOLYGON (((-13611729.441 4553955.403, -13...",060014014003,60014014003

In [42]:
checkgdf = race2019blockgdf.newgeoid.value_counts()
checkgdf.sort_values()

60014001001    1
60014003003    1
60014003004    1
60014004001    1
60014004002    1
              ..
60014104003    1
60014105001    1
60014099001    1
60014098003    1
60019832001    1
Name: newgeoid, Length: 330, dtype: int64

In [7]:
CountClose2019gdf = gpd.read_file('CountClose2019.geojson')
CountClose2019gdf.sample(3)

,statefp10,mtfcc10,uace10,name10,intptlat10,blockce10,awater10,funcstat10,aland10,geoid10,...,intptlon10,ur10,countyfp10,counts,counts_lag,counts_lag_diff,closure_median,closure_lag,closure_lag_diff,geometry
1602,06,G5040,,Block 2005,+37.7964926,2005,0,S,64534,060014064002005,...,-122.2205017,,001,8,2.75,5.25,72.0,66.4375,5.5625,"MULTIPOLYGON (((-13605701.490 4550485.960, -13..."
1322,06,G5040,,Block 1004,+37.7992491,1004,0,S,13318,060014066021004,...,-122.2137832,,001,1,2.50,-1.50,4.0,69.7500,-65.7500,"MULTIPOLYGON (((-13604672.119 4551138.788, -13..."
847,06,G5040,,Block 1004,+37.7753633,1004,0,S,16012,060014072001004,...,-122.2156399,,001,1,1.50,-0.50,55.0,54.3125,0.6875,"MULTIPOLYGON (((-13604868.375 4547789.150, -13..."

In [40]:
CountClose2019gdf['newgeoid'] = CountClose2019gdf['geoid10'].str[1:12]
CountClose2019gdf.sample(3)

,statefp10,mtfcc10,uace10,name10,intptlat10,blockce10,awater10,funcstat10,aland10,geoid10,...,ur10,countyfp10,counts,counts_lag,counts_lag_diff,closure_median,closure_lag,closure_lag_diff,geometry,newgeoid
72,06,G5040,,Block 3019,+37.8452564,3019,0,S,269217,060014044003019,...,,001,19,3.50,15.50,9.5,157.4375,-147.9375,"MULTIPOLYGON (((-13602927.854 4557562.178, -13...",60014044003
141,06,G5040,,Block 3010,+37.7827396,3010,0,S,573,060014070003010,...,,001,1,2.00,-1.00,5.0,148.5000,-143.5000,"MULTIPOLYGON (((-13603702.638 4548748.152, -13...",60014070003
1121,06,G5040,,Block 1013,+37.8030937,1013,0,S,10021,060014031001013,...,,001,1,1.75,-0.75,185.0,87.8750,97.1250,"MULTIPOLYGON (((-13611631.925 4551565.106, -13...",60014031001

In [44]:
check2gdf = CountClose2019gdf.newgeoid.value_counts()
check2gdf.sort_values()

60014067002     1
60014081003     1
60014239021     1
60014038001     1
60014096002     1
               ..
60014105001    18
60014089002    19
60014061001    22
60014073002    22
60014060001    25
Name: newgeoid, Length: 332, dtype: int64

In [43]:
new2019df = CountClose2019gdf[['newgeoid', 'counts','counts_lag','counts_lag_diff','closure_median','closure_lag','closure_lag_diff']]
new2019df.sample(3)

,newgeoid,counts,counts_lag,counts_lag_diff,closure_median,closure_lag,closure_lag_diff
889,60014075002,1,2.5,-1.5,21.0,201.0000,-180.0000
2,60014054011,3,2.0,1.0,7.0,91.6250,-84.6250
198,60014017002,2,1.0,1.0,26.0,40.8125,-14.8125

In [22]:
Merged2019gdf = race2019blockgdf.merge(new2019df,on='newgeoid')
Merged2019gdf.sample(3)

KeyError: 'geometry'

In [45]:
basic311gdf = gpd.read_file('Data/2019_OAK_311_NoBlank.csv')
basic311gdf.sample(3)

,REQUESTID,DATETIMEINIT,SOURCE,DESCRIPTION,REQCATEGORY,STATUS,REFERREDTO,DATETIMECLOSED,SRX,SRY,COUNCILDISTRICT,BEAT,Time to Close,LAT,LONG,geometry
114,936740,8/20/19 15:24,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,8/22/19 14:22,6077162.617,2110280.902,CCD6,29X,2,37.77852637,-122.1765296,None
1689,867533,1/18/19 12:53,SeeClickFix,Streets - Potholes/Depression,STREETSW,OPEN,,,6063579.497,2113340.471,CCD5,21Y,Open,37.78624994,-122.2237158,None
1943,882557,3/1/19 15:29,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,3/22/19 07:54,6048049.842,2128255.049,CCD3,07X,21,37.82640504,-122.2784268,None

In [47]:
basic311gdf['LAT'] = basic311gdf['LAT'].astype('float64')

In [48]:
basic311gdf['LONG'] = basic311gdf['LONG'].astype('float64')

In [69]:
race2019blockgdf = race2019blockgdf.to_crs(4326)

In [71]:
joinedgdf = gpd.sjoin(basic311gdf, race2019blockgdf, how="left")

In [73]:
pd.set_option('display.max_columns', None)
joinedgdf

,REQUESTID,DATETIMEINIT,SOURCE,DESCRIPTION,REQCATEGORY,STATUS,REFERREDTO,DATETIMECLOSED,SRX,SRY,COUNCILDISTRICT,BEAT,Time to Close,LAT,LONG,geometry,index_right,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geoid10,newgeoid
0,927576,7/23/19 15:38,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,7/26/19 13:45,6055962.501,2132386.75,CCD1,12Y,3,37.838160,-122.251303,POINT (-122.25130 37.83816),4.0,15000US060014003002,"Block Group 2, Alameda, CA",1237.0,1008.0,18.0,0.0,113.0,0.0,0.0,0.0,98.0,81.487470,1.455133,0.000000,9.135004,0.0,0.000000,0.000000,7.922393,060014003002,60014003002
1,918469,6/25/19 08:34,SeeClickFix,Streets - Guardrail Repair,STREETSW,CLOSED,,7/10/19 18:11,6063364.409,2136673.615,CCD1,13Y,15,37.850308,-122.225949,POINT (-122.22595 37.85031),0.0,15000US060014001001,"Block Group 1, Alameda, CA",3120.0,2317.0,107.0,0.0,391.0,0.0,0.0,187.0,118.0,74.262821,3.429487,0.000000,12.532051,0.0,0.000000,5.993590,3.782051,060014001001,60014001001
2,922854,7/9/19 12:17,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,7/22/19 16:40,6055410.001,2116416.751,CCD2,19X,13,37.794280,-122.252180,POINT (-122.25218 37.79428),167.0,15000US060014060003,"Block Group 3, Alameda, CA",2011.0,326.0,430.0,0.0,809.0,0.0,0.0,46.0,400.0,16.210840,21.382397,0.000000,40.228742,0.0,0.000000,2.287419,19.890602,060014060003,60014060003
3,917741,6/22/19 16:00,SeeClickFix,Streets - Street Deterioration,STREETSW,OPEN,,,6076796.539,2120845.822,CCD4,22Y,Open,37.807518,-122.178452,POINT (-122.17845 37.80752),116.0,15000US060014046004,"Block Group 4, Alameda, CA",1421.0,1147.0,71.0,0.0,98.0,0.0,14.0,15.0,76.0,80.717804,4.996481,0.000000,6.896552,0.0,0.985222,1.055595,5.348346,060014046004,60014046004
4,927190,7/22/19 16:17,SeeClickFix,Streets - Street Deterioration,STREETSW,OPEN,,,6071960.1,2128430.85,CCD4,13Z,Open,37.828107,-122.195666,POINT (-122.19567 37.82811),114.0,15000US060014046002,"Block Group 2, Alameda, CA",757.0,511.0,48.0,0.0,62.0,0.0,15.0,28.0,93.0,67.503303,6.340819,0.000000,8.190225,0.0,1.981506,3.698811,12.285337,060014046002,60014046002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5280,923771,7/11/19 17:33,SeeClickFix,Streets/Sidewalks - Other/Complex,STREETSW,OPEN,,,6085411.691,2097300.792,CCD7,32Y,Open,37.743286,-122.147201,POINT (-122.14720 37.74329),316.0,15000US060014100002,"Block Group 2, Alameda, CA",2257.0,504.0,1197.0,8.0,44.0,0.0,32.0,294.0,178.0,22.330527,53.035002,0.354453,1.949490,0.0,1.417811,13.026141,7.886575,060014100002,60014100002
5281,921704,7/5/19 14:02,Email,Streets - Potholes/Depression,STREETSW,OPEN,,,6056022.087,2123898.335,CCD2,14Y,Open,37.814855,-122.250547,POINT (-122.25055 37.81486),92.0,15000US060014039003,"Block Group 3, Alameda, CA",1450.0,863.0,267.0,0.0,161.0,0.0,0.0,115.0,44.0,59.517241,18.413793,0.000000,11.103448,0.0,0.000000,7.931034,3.034483,060014039003,60014039003
5282,916830,6/19/19 12:43,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,7/1/19 06:25,6058128,2118764.25,CCD2,17Y,12,37.800866,-122.242927,POINT (-122.24293 37.80087),152.0,15000US060014056003,"Block Group 3, Alameda, CA",1342.0,397.0,254.0,0.0,247.0,0.0,23.0,124.0,297.0,29.582712,18.926975,0.000000,18.405365,0.0,1.713860,9.239940,22.131148,060014056003,60014056003
5283,916568,6/18/19 19:20,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,6/24/19 14:52,6064486.543,2134004.608,CCD1,13Y,6,37.843036,-122.221893,POINT (-122.22189 37.84304),105.0,15000US060014044001,"Block Group 1, Alameda, CA",2373.0,1575.0,116.0,0.0,322.0,0.0,0.0,181.0,179.0,66.371681,4.888327,0.000000,13.569322,0.0,0.000000,7.627476,7.543194,060014044001,60014044001
5284,928990,7/28/19 19:02,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,7/30/19 06:15,6054832.646,2131573.798,CCD1,12Y,2,37.835869,-122.255162,POINT (-122.25516 37.83587),4.0,15000US060014003002,"Block Group 2, Alameda, CA",1237.0,1008.0,18.0,0.0,113.0,0.0,0.0,0.0,98.0,81.487470,1.455133,0.000000,9.135004,0.0,0.000000,0.000000,7.922393,060014003002,60014003002

In [75]:
joinedgdf['newgeoid.value_counts()

60014045024    96
60014001001    75
60014073002    71
60014061001    63
60014044003    62
               ..
60014086004     2
60014058004     1
60014024002     1
60014014002     1
60014002001     1
Name: newgeoid, Length: 325, dtype: int64

In [78]:
countdf = joinedgdf['newgeoid'].value_counts().rename_axis('newgeoid').reset_index(name='counts')
print (countdf)

        newgeoid  counts
0    60014045024      96
1    60014001001      75
2    60014073002      71
3    60014061001      63
4    60014044003      62
..           ...     ...
320  60014086004       2
321  60014058004       1
322  60014024002       1
323  60014014002       1
324  60014002001       1

[325 rows x 2 columns]

In [81]:
blockcountracegdf = race2019blockgdf.merge(countdf,on='newgeoid')
blockcountracegdf.sample(3)

,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geometry,geoid10,newgeoid,counts
85,15000US060014038004,"Block Group 4, Alameda, CA",1349.0,1057.0,118.0,0.0,95.0,0.0,0.0,61.0,18.0,78.354337,8.747220,0.0,7.042254,0.000000,0.0,4.521868,1.334322,"MULTIPOLYGON (((-122.24624 37.81446, -122.2462...",060014038004,60014038004,17
136,15000US060014053022,"Block Group 2, Alameda, CA",1327.0,318.0,203.0,0.0,608.0,0.0,0.0,96.0,102.0,23.963828,15.297664,0.0,45.817634,0.000000,0.0,7.234363,7.686511,"MULTIPOLYGON (((-122.25548 37.79724, -122.2553...",060014053022,60014053022,10
285,15000US060014093002,"Block Group 2, Alameda, CA",1573.0,120.0,428.0,0.0,0.0,19.0,0.0,0.0,1006.0,7.628735,27.209154,0.0,0.000000,1.207883,0.0,0.000000,63.954228,"MULTIPOLYGON (((-122.17267 37.73642, -122.1722...",060014093002,60014093002,15

In [83]:
blockcountracegdf.drop(columns='geoid10')

,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geometry,newgeoid,counts
0,15000US060014001001,"Block Group 1, Alameda, CA",3120.0,2317.0,107.0,0.0,391.0,0.0,0.0,187.0,118.0,74.262821,3.429487,0.000000,12.532051,0.000000,0.000000,5.993590,3.782051,"MULTIPOLYGON (((-122.24692 37.88544, -122.2466...",60014001001,75
1,15000US060014002001,"Block Group 1, Alameda, CA",990.0,761.0,13.0,4.0,41.0,0.0,0.0,75.0,96.0,76.868687,1.313131,0.404040,4.141414,0.000000,0.000000,7.575758,9.696970,"MULTIPOLYGON (((-122.25508 37.84607, -122.2542...",60014002001,1
2,15000US060014002002,"Block Group 2, Alameda, CA",1017.0,714.0,39.0,0.0,130.0,0.0,0.0,56.0,78.0,70.206490,3.834808,0.000000,12.782694,0.000000,0.000000,5.506391,7.669617,"MULTIPOLYGON (((-122.25792 37.84261, -122.2577...",60014002002,12
3,15000US060014003001,"Block Group 1, Alameda, CA",1134.0,735.0,0.0,0.0,274.0,0.0,0.0,50.0,75.0,64.814815,0.000000,0.000000,24.162257,0.000000,0.000000,4.409171,6.613757,"MULTIPOLYGON (((-122.25186 37.84475, -122.2517...",60014003001,30
4,15000US060014003002,"Block Group 2, Alameda, CA",1237.0,1008.0,18.0,0.0,113.0,0.0,0.0,0.0,98.0,81.487470,1.455133,0.000000,9.135004,0.000000,0.000000,0.000000,7.922393,"MULTIPOLYGON (((-122.26231 37.83786, -122.2622...",60014003002,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,15000US060014104001,"Block Group 1, Alameda, CA",1290.0,22.0,408.0,9.0,69.0,0.0,0.0,26.0,756.0,1.705426,31.627907,0.697674,5.348837,0.000000,0.000000,2.015504,58.604651,"MULTIPOLYGON (((-122.16321 37.74434, -122.1629...",60014104001,7
321,15000US060014104002,"Block Group 2, Alameda, CA",1400.0,34.0,696.0,3.0,97.0,0.0,0.0,10.0,560.0,2.428571,49.714286,0.214286,6.928571,0.000000,0.000000,0.714286,40.000000,"MULTIPOLYGON (((-122.16273 37.74065, -122.1625...",60014104002,6
322,15000US060014104003,"Block Group 3, Alameda, CA",1787.0,230.0,401.0,0.0,286.0,0.0,0.0,50.0,820.0,12.870733,22.439843,0.000000,16.004477,0.000000,0.000000,2.797985,45.886961,"MULTIPOLYGON (((-122.16921 37.74276, -122.1691...",60014104003,9
323,15000US060014105001,"Block Group 1, Alameda, CA",2705.0,403.0,1652.0,7.0,294.0,24.0,7.0,52.0,266.0,14.898336,61.072089,0.258780,10.868762,0.887246,0.258780,1.922366,9.833641,"MULTIPOLYGON (((-122.29360 37.80530, -122.2935...",60014105001,35
324,15000US060019832001,"Block Group 1, Alameda, CA",583.0,308.0,53.0,9.0,138.0,3.0,5.0,20.0,47.0,52.830189,9.090909,1.543739,23.670669,0.514580,0.857633,3.430532,8.061750,"MULTIPOLYGON (((-122.28417 37.79402, -122.2838...",60019832001,16

In [97]:
closeracegdf = joinedgdf[joinedgdf['Time to Close']!='Open']
closeracegdf.sample(3)

,REQUESTID,DATETIMEINIT,SOURCE,DESCRIPTION,REQCATEGORY,STATUS,REFERREDTO,DATETIMECLOSED,SRX,SRY,COUNCILDISTRICT,BEAT,Time to Close,LAT,LONG,geometry,index_right,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geoid10,newgeoid
4300,903314,5/9/19 11:04,Phone,Streets - Potholes/Depression,STREETSW,CLOSED,,10/31/19 06:12,6074081.999,2125388.999,CCD4,22Y,175,37.819859,-122.188130,POINT (-122.18813 37.81986),116.0,15000US060014046004,"Block Group 4, Alameda, CA",1421.0,1147.0,71.0,0.0,98.0,0.0,14.0,15.0,76.0,80.717804,4.996481,0.0,6.896552,0.000000,0.985222,1.055595,5.348346,060014046004,60014046004
3684,902049,5/6/19 10:20,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,3/16/21 13:53,6046469.5,2126866.749,CCD3,07X,680,37.822510,-122.283806,POINT (-122.28381 37.82251),44.0,15000US060014015002,"Block Group 2, Alameda, CA",1041.0,453.0,226.0,0.0,49.0,0.0,0.0,83.0,230.0,43.515850,21.709894,0.0,4.707012,0.000000,0.000000,7.973103,22.094140,060014015002,60014015002
4955,916829,6/19/19 12:41,SeeClickFix,Streets - Potholes/Depression,STREETSW,CLOSED,,7/1/19 06:25,6057855.501,2118529.749,CCD2,17Y,12,37.800208,-122.243855,POINT (-122.24385 37.80021),148.0,15000US060014055003,"Block Group 3, Alameda, CA",837.0,195.0,125.0,0.0,438.0,25.0,0.0,0.0,54.0,23.297491,14.934289,0.0,52.329749,2.986858,0.000000,0.000000,6.451613,060014055003,60014055003

In [98]:
closeracegdf['Time to Close'] = closeracegdf['Time to Close'].astype('int64')

/opt/conda/lib/python3.9/site-packages/geopandas/geodataframe.py:1322: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super(GeoDataFrame, self).__setitem__(key, value)

In [99]:
closeddf_grouped = closeracegdf.groupby(['newgeoid']).median()[['Time to Close']]
closeddf_grouped.sample(3)

             Time to Close
newgeoid
60014081004            5.0
60014063001           58.0
60014049002           15.0

In [100]:
closetimedf = closedgdf_grouped.rename_axis('newgeoid').reset_index('newgeoid')
print (closetimedf)

        newgeoid  Time to Close
0    60014001001           25.5
1    60014002002           15.0
2    60014003001           42.0
3    60014003002           92.0
4    60014003003          294.5
..           ...            ...
314  60014104001           15.5
315  60014104002           10.0
316  60014104003           14.0
317  60014105001           37.0
318  60019832001           37.0

[319 rows x 2 columns]

In [101]:
closetimedf.columns = ['newgeoid', 'closure_median']
closetimedf

        newgeoid  closure_median
0    60014001001            25.5
1    60014002002            15.0
2    60014003001            42.0
3    60014003002            92.0
4    60014003003           294.5
..           ...             ...
314  60014104001            15.5
315  60014104002            10.0
316  60014104003            14.0
317  60014105001            37.0
318  60019832001            37.0

[319 rows x 2 columns]

In [102]:
blockcloseracegdf = race2019blockgdf.merge(closetimedf,on='newgeoid')
blockcloseracegdf

,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geometry,geoid10,newgeoid,closure_median
0,15000US060014001001,"Block Group 1, Alameda, CA",3120.0,2317.0,107.0,0.0,391.0,0.0,0.0,187.0,118.0,74.262821,3.429487,0.000000,12.532051,0.000000,0.000000,5.993590,3.782051,"MULTIPOLYGON (((-122.24692 37.88544, -122.2466...",060014001001,60014001001,25.5
1,15000US060014002002,"Block Group 2, Alameda, CA",1017.0,714.0,39.0,0.0,130.0,0.0,0.0,56.0,78.0,70.206490,3.834808,0.000000,12.782694,0.000000,0.000000,5.506391,7.669617,"MULTIPOLYGON (((-122.25792 37.84261, -122.2577...",060014002002,60014002002,15.0
2,15000US060014003001,"Block Group 1, Alameda, CA",1134.0,735.0,0.0,0.0,274.0,0.0,0.0,50.0,75.0,64.814815,0.000000,0.000000,24.162257,0.000000,0.000000,4.409171,6.613757,"MULTIPOLYGON (((-122.25186 37.84475, -122.2517...",060014003001,60014003001,42.0
3,15000US060014003002,"Block Group 2, Alameda, CA",1237.0,1008.0,18.0,0.0,113.0,0.0,0.0,0.0,98.0,81.487470,1.455133,0.000000,9.135004,0.000000,0.000000,0.000000,7.922393,"MULTIPOLYGON (((-122.26231 37.83786, -122.2622...",060014003002,60014003002,92.0
4,15000US060014003003,"Block Group 3, Alameda, CA",1136.0,632.0,373.0,0.0,106.0,0.0,0.0,0.0,25.0,55.633803,32.834507,0.000000,9.330986,0.000000,0.000000,0.000000,2.200704,"MULTIPOLYGON (((-122.26563 37.83764, -122.2655...",060014003003,60014003003,294.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,15000US060014104001,"Block Group 1, Alameda, CA",1290.0,22.0,408.0,9.0,69.0,0.0,0.0,26.0,756.0,1.705426,31.627907,0.697674,5.348837,0.000000,0.000000,2.015504,58.604651,"MULTIPOLYGON (((-122.16321 37.74434, -122.1629...",060014104001,60014104001,15.5
315,15000US060014104002,"Block Group 2, Alameda, CA",1400.0,34.0,696.0,3.0,97.0,0.0,0.0,10.0,560.0,2.428571,49.714286,0.214286,6.928571,0.000000,0.000000,0.714286,40.000000,"MULTIPOLYGON (((-122.16273 37.74065, -122.1625...",060014104002,60014104002,10.0
316,15000US060014104003,"Block Group 3, Alameda, CA",1787.0,230.0,401.0,0.0,286.0,0.0,0.0,50.0,820.0,12.870733,22.439843,0.000000,16.004477,0.000000,0.000000,2.797985,45.886961,"MULTIPOLYGON (((-122.16921 37.74276, -122.1691...",060014104003,60014104003,14.0
317,15000US060014105001,"Block Group 1, Alameda, CA",2705.0,403.0,1652.0,7.0,294.0,24.0,7.0,52.0,266.0,14.898336,61.072089,0.258780,10.868762,0.887246,0.258780,1.922366,9.833641,"MULTIPOLYGON (((-122.29360 37.80530, -122.2935...",060014105001,60014105001,37.0
318,15000US060019832001,"Block Group 1, Alameda, CA",583.0,308.0,53.0,9.0,138.0,3.0,5.0,20.0,47.0,52.830189,9.090909,1.543739,23.670669,0.514580,0.857633,3.430532,8.061750,"MULTIPOLYGON (((-122.28417 37.79402, -122.2838...",060019832001,60019832001,37.0

In [103]:
blockcloseracegdf.drop(columns='geoid10')

,geoid,name,Total,White alone,Black or African American alone,American Indian and Alaska Native alone,Asian alone,Native Hawaiian and Other Pacific Islander alone,Some other race alone,Two or more races,Hispanic or Latino,Percent White alone,Percent Black or African American alone,Percent American Indian and Alaska Native alone,Percent Asian alone,Percent Native Hawaiian and Other Pacific Islander alone,Percent Some other race alone,Percent Two or more races,Percent Hispanic or Latino,geometry,newgeoid,closure_median
0,15000US060014001001,"Block Group 1, Alameda, CA",3120.0,2317.0,107.0,0.0,391.0,0.0,0.0,187.0,118.0,74.262821,3.429487,0.000000,12.532051,0.000000,0.000000,5.993590,3.782051,"MULTIPOLYGON (((-122.24692 37.88544, -122.2466...",60014001001,25.5
1,15000US060014002002,"Block Group 2, Alameda, CA",1017.0,714.0,39.0,0.0,130.0,0.0,0.0,56.0,78.0,70.206490,3.834808,0.000000,12.782694,0.000000,0.000000,5.506391,7.669617,"MULTIPOLYGON (((-122.25792 37.84261, -122.2577...",60014002002,15.0
2,15000US060014003001,"Block Group 1, Alameda, CA",1134.0,735.0,0.0,0.0,274.0,0.0,0.0,50.0,75.0,64.814815,0.000000,0.000000,24.162257,0.000000,0.000000,4.409171,6.613757,"MULTIPOLYGON (((-122.25186 37.84475, -122.2517...",60014003001,42.0
3,15000US060014003002,"Block Group 2, Alameda, CA",1237.0,1008.0,18.0,0.0,113.0,0.0,0.0,0.0,98.0,81.487470,1.455133,0.000000,9.135004,0.000000,0.000000,0.000000,7.922393,"MULTIPOLYGON (((-122.26231 37.83786, -122.2622...",60014003002,92.0
4,15000US060014003003,"Block Group 3, Alameda, CA",1136.0,632.0,373.0,0.0,106.0,0.0,0.0,0.0,25.0,55.633803,32.834507,0.000000,9.330986,0.000000,0.000000,0.000000,2.200704,"MULTIPOLYGON (((-122.26563 37.83764, -122.2655...",60014003003,294.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,15000US060014104001,"Block Group 1, Alameda, CA",1290.0,22.0,408.0,9.0,69.0,0.0,0.0,26.0,756.0,1.705426,31.627907,0.697674,5.348837,0.000000,0.000000,2.015504,58.604651,"MULTIPOLYGON (((-122.16321 37.74434, -122.1629...",60014104001,15.5
315,15000US060014104002,"Block Group 2, Alameda, CA",1400.0,34.0,696.0,3.0,97.0,0.0,0.0,10.0,560.0,2.428571,49.714286,0.214286,6.928571,0.000000,0.000000,0.714286,40.000000,"MULTIPOLYGON (((-122.16273 37.74065, -122.1625...",60014104002,10.0
316,15000US060014104003,"Block Group 3, Alameda, CA",1787.0,230.0,401.0,0.0,286.0,0.0,0.0,50.0,820.0,12.870733,22.439843,0.000000,16.004477,0.000000,0.000000,2.797985,45.886961,"MULTIPOLYGON (((-122.16921 37.74276, -122.1691...",60014104003,14.0
317,15000US060014105001,"Block Group 1, Alameda, CA",2705.0,403.0,1652.0,7.0,294.0,24.0,7.0,52.0,266.0,14.898336,61.072089,0.258780,10.868762,0.887246,0.258780,1.922366,9.833641,"MULTIPOLYGON (((-122.29360 37.80530, -122.2935...",60014105001,37.0
318,15000US060019832001,"Block Group 1, Alameda, CA",583.0,308.0,53.0,9.0,138.0,3.0,5.0,20.0,47.0,52.830189,9.090909,1.543739,23.670669,0.514580,0.857633,3.430532,8.061750,"MULTIPOLYGON (((-122.28417 37.79402, -122.2838...",60019832001,37.0

In [104]:
blockcloseracegdf.to_file("blockcloserace2019gdf.geojson", driver='GeoJSON')

In [105]:
blockcountracegdf.to_file("blockcountrace2019gdf.geojson", driver='GeoJSON')